name: Check PullRequest Pattern
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    # Don't run on pull requests from deploy branches as these never have ticket numbers
    # Also don't run on pull requests from dependabot
    if: startsWith(github.head_ref, 'deploy/v') == false && startsWith(github.actor, 'dependabot') == false
    steps:
      - name: Check PR
        uses: jvbsl/pr-lint-action@feature/body-regex
        with:
          title-regex: '\[#PAX-I\d+\]\s*(\w+\W+){2,}'
          on-failed-regex-comment: "Your pull request must have a meaningful title and contain the ticket e.g. [#PAX-I1234]."
          body-regex: '(\w+\W+){5,}'
          on-failed-body-regex-comment: "Your pull request must have a meaningful description."
          on-failed-regex-fail-action: false
          on-failed-regex-create-review: false
          on-failed-regex-request-changes: true
          on-failed-body-regex-fail-action: false
          on-failed-body-regex-create-review: false
          on-failed-body-regex-request-changes: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Extract Ticket
        run: |
          PR_NUM=$(echo ${{ toJSON(github.event.pull_request.title) }} | grep -o -P "PAX-I[0-9]+" | head -n 1)
          echo "PR_NUMBER=#$PR_NUM" >> $GITHUB_ENV
        shell: bash
      - name: Add PAX Reference
        uses: actions/github-script@v7
        if: ${{ !contains(github.event.pull_request.body, env.PR_NUMBER) }}
        with:
          script: |
            const pr = context.payload.pull_request;
            const paxReference = "${{ env.PR_NUMBER }}";

            const body = pr.body ? `${pr.body}\n\n${paxReference}` : paxReference;
            
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              body: body
            });
